<a href="https://colab.research.google.com/github/NuttharikaTht/MovieIMDbScoreModel/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Movie IMDb Rating Predictation Model**

code study and reference : https://www.kaggle.com/code/saurav9786/imdb-score-prediction-for-movies/notebook


dataset : https://www.kaggle.com/datasets/carolzhangdc/imdb-5000-movie-dataset

# Import Library and Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from plotnine import *

In [2]:
df = pd.read_csv("./movie_metadata.csv")

# Dataset Checking

In [3]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [4]:
df.shape

(5043, 28)

In [5]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
m

In [6]:
df.describe().T

count          mean           std      min  \
num_critic_for_reviews     4993.0  1.401943e+02  1.216017e+02     1.00   
duration                   5028.0  1.072011e+02  2.519744e+01     7.00   
director_facebook_likes    4939.0  6.865092e+02  2.813329e+03     0.00   
actor_3_facebook_likes     5020.0  6.450098e+02  1.665042e+03     0.00   
actor_1_facebook_likes     5036.0  6.560047e+03  1.502076e+04     0.00   
gross                      4159.0  4.846841e+07  6.845299e+07   162.00   
num_voted_users            5043.0  8.366816e+04  1.384853e+05     5.00   
cast_total_facebook_likes  5043.0  9.699064e+03  1.816380e+04     0.00   
facenumber_in_poster       5030.0  1.371173e+00  2.013576e+00     0.00   
num_user_for_reviews       5022.0  2.727708e+02  3.779829e+02     1.00   
budget                     4551.0  3.975262e+07  2.061149e+08   218.00   
title_year                 4935.0  2.002471e+03  1.247460e+01  1916.00   
actor_2_facebook_likes     5030.0  1.651754e+03  4.042439e+03     0.00   
imdb_score                 5043.0  6.442138e+00  1.125116e+00     1.60   
aspect_ratio               4714.0  2.220403e+00  1.385113e+00     1.18   
movie_facebook_likes       5043.0  7.525965e+03  1.932045e+04     0.00   

                                  25%          50%          75%           max  
num_critic_for_reviews          50.00       110.00       195.00  8.130000e+02  
duration                        93.00       103.00       118.00  5.110000e+02  
director_facebook_likes          7.00        49.00       194.50  2.300000e+04  
actor_3_facebook_likes         133.00       371.50       636.00  2.300000e+04  
actor_1_facebook_likes         614.00       988.00     11000.00  6.400000e+05  
gross                      5340987.50  25517500.00  62309437.50  7.605058e+08  
num_voted_users               8593.50     34359.00     96309.00  1.689764e+06  
cast_total_facebook_likes     1411.00      3090.00     13756.50  6.567300e+05  
facenumber_in_poster             0.00         1.00         2.00  4.300000e+01  
num_user_for_reviews            65.00       156.00       326.00  5.060000e+03  
budget                     6000000.00  20000000.00  45000000.00  1.221550e+10  
title_year                    1999.00      2005.00      2011.00  2.016000e+03  
actor_2_facebook_likes         281.00       595.00       918.00  1.370000e+05  
imdb_score                       5.80         6.60         7.20  9.500000e+00  
aspect_ratio                     1.85         2.35         2.35  1.600000e+01  
movie_facebook_likes             0.00       166.00      3000.00  3.490000e+05

# Data Preparation

## Removing

In [7]:
# Removing Attrb that not relevant

df.drop( 'movie_imdb_link', axis=1, inplace = True)
df.drop('movie_title',axis=1,inplace=True)
df.drop( 'num_critic_for_reviews', axis=1, inplace = True)
df.drop( 'gross', axis=1, inplace = True)
df.drop( 'num_voted_users', axis=1, inplace = True)
df.drop( 'num_user_for_reviews', axis=1, inplace = True)
df.drop( 'title_year', axis=1, inplace = True)
#df.drop( 'movie_facebook_likes', axis=1, inplace = True)
df.drop( 'cast_total_facebook_likes',axis=1,inplace=True)
#df.drop( 'director_facebook_likes',axis=1,inplace=True)
#df.drop( 'actor_3_facebook_likes',axis=1,inplace=True)
#df.drop( 'actor_1_facebook_likes',axis=1,inplace=True)
#df.drop( 'actor_2_facebook_likes',axis=1,inplace=True)
df.drop( 'aspect_ratio',axis=1,inplace=True)
#df.drop( 'facenumber_in_poster',axis=1,inplace=True)

In [8]:
df.drop( 'director_name', axis=1, inplace = True)
df.drop( 'actor_1_name', axis=1, inplace = True)
df.drop( 'actor_2_name', axis=1, inplace = True)
df.drop( 'actor_3_name', axis=1, inplace = True)

In [9]:
df.columns

Index(['color', 'duration', 'director_facebook_likes',
       'actor_3_facebook_likes', 'actor_1_facebook_likes', 'genres',
       'facenumber_in_poster', 'plot_keywords', 'language', 'country',
       'content_rating', 'budget', 'actor_2_facebook_likes', 'imdb_score',
       'movie_facebook_likes'],
      dtype='object')

In [10]:
# Checking NaN Value in each Attrb
df.isna().any()

color                       True
duration                    True
director_facebook_likes     True
actor_3_facebook_likes      True
actor_1_facebook_likes      True
genres                     False
facenumber_in_poster        True
plot_keywords               True
language                    True
country                     True
content_rating              True
budget                      True
actor_2_facebook_likes      True
imdb_score                 False
movie_facebook_likes       False
dtype: bool

In [11]:
#Checking Number of NaN Value in each Attrb
df.isna().sum()

color                       19
duration                    15
director_facebook_likes    104
actor_3_facebook_likes      23
actor_1_facebook_likes       7
genres                       0
facenumber_in_poster        13
plot_keywords              153
language                    12
country                      5
content_rating             303
budget                     492
actor_2_facebook_likes      13
imdb_score                   0
movie_facebook_likes         0
dtype: int64

In [12]:
new_df = df.dropna()

In [13]:
new_df.isna().sum()

color                      0
duration                   0
director_facebook_likes    0
actor_3_facebook_likes     0
actor_1_facebook_likes     0
genres                     0
facenumber_in_poster       0
plot_keywords              0
language                   0
country                    0
content_rating             0
budget                     0
actor_2_facebook_likes     0
imdb_score                 0
movie_facebook_likes       0
dtype: int64

In [14]:
new_df.shape

(4256, 15)

In [15]:
df = new_df

In [16]:
df.drop_duplicates(inplace=True)
df.shape

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


(4158, 15)

In [17]:
#Check Amount in Each Language of Movies
df["language"].value_counts()

English       3973
French          40
Spanish         28
Mandarin        16
Japanese        13
German          10
Italian          8
Cantonese        7
Hindi            7
Portuguese       6
Russian          5
Korean           5
Norwegian        4
Persian          3
Danish           3
Thai             3
Dutch            3
Zulu             2
Aboriginal       2
None             2
Indonesian       2
Dari             2
Hebrew           2
Mongolian        1
Romanian         1
Vietnamese       1
Arabic           1
Filipino         1
Czech            1
Maya             1
Kazakh           1
Aramaic          1
Hungarian        1
Bosnian          1
Swedish          1
Name: language, dtype: int64

In [18]:
#Drop Language Column because Most of Movie is in English

df.drop('language',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [19]:
df["country"].value_counts()

USA               3251
UK                 355
France             116
Canada              89
Germany             85
Australia           46
Spain               25
Japan               18
Italy               16
China               14
Hong Kong           13
New Zealand         12
Denmark              9
South Korea          9
South Africa         8
Norway               7
Mexico               7
Ireland              7
India                7
Russia               6
Brazil               6
Argentina            4
Iran                 4
Thailand             4
Netherlands          4
Czech Republic       3
Taiwan               2
Israel               2
Hungary              2
West Germany         2
Romania              2
Belgium              1
Iceland              1
Sweden               1
Switzerland          1
Afghanistan          1
Indonesia            1
Kyrgyzstan           1
New Line             1
Poland               1
Colombia             1
Soviet Union         1
Finland              1
Bahamas    

In [20]:
#Drop Country Column because Most of Movie is in USA

df.drop('country',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [21]:
df["color"].value_counts()

Color               3986
 Black and White     172
Name: color, dtype: int64

In [22]:
#Drop Country Column because Most of Movie is in Color
df.drop('color',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [23]:
#Drop Plot Keywords Column because it has too many unique variables per movie
df.drop('plot_keywords',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [24]:
df.head()

duration  director_facebook_likes  actor_3_facebook_likes  \
0     178.0                      0.0                   855.0   
1     169.0                    563.0                  1000.0   
2     148.0                      0.0                   161.0   
3     164.0                  22000.0                 23000.0   
5     132.0                    475.0                   530.0   

   actor_1_facebook_likes                           genres  \
0                  1000.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0         Action|Adventure|Fantasy   
2                 11000.0        Action|Adventure|Thriller   
3                 27000.0                  Action|Thriller   
5                   640.0          Action|Adventure|Sci-Fi   

   facenumber_in_poster content_rating       budget  actor_2_facebook_likes  \
0                   0.0          PG-13  237000000.0                   936.0   
1                   0.0          PG-13  300000000.0                  5000.0   
2                   1.0          PG-13  245000000.0                   393.0   
3                   0.0          PG-13  250000000.0                 23000.0   
5                   1.0          PG-13  263700000.0                   632.0   

   imdb_score  movie_facebook_likes  
0         7.9                 33000  
1         7.1                     0  
2         6.8                 85000  
3         8.5                164000  
5         6.6                 24000

In [25]:
df.shape

(4158, 11)

In [26]:
df.columns

Index(['duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'genres', 'facenumber_in_poster',
       'content_rating', 'budget', 'actor_2_facebook_likes', 'imdb_score',
       'movie_facebook_likes'],
      dtype='object')

## Content Rating Column

In [27]:
df = pd.get_dummies(data = df, columns = ['content_rating'] , prefix = ['content_rating'] , drop_first = True)

## **Split genres to Columns (One-Hot)**

In [28]:
df['genres'] = df['genres'].str.replace('|', ',')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


In [29]:
from sklearn.preprocessing import MultiLabelBinarizer

In [30]:
mlb = MultiLabelBinarizer()

In [31]:
df1 = df.join(pd.DataFrame(mlb.fit_transform(df['genres'].str.split(',')),
                           columns=mlb.classes_))

In [32]:
df1.columns

Index(['duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'genres', 'facenumber_in_poster', 'budget',
       'actor_2_facebook_likes', 'imdb_score', 'movie_facebook_likes',
       'content_rating_G', 'content_rating_GP', 'content_rating_M',
       'content_rating_NC-17', 'content_rating_Not Rated', 'content_rating_PG',
       'content_rating_PG-13', 'content_rating_Passed', 'content_rating_R',
       'content_rating_TV-14', 'content_rating_TV-G', 'content_rating_TV-PG',
       'content_rating_Unrated', 'content_rating_X', 'Action', 'Adventure',
       'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Family', 'Fantasy', 'Film-Noir', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [33]:
for g in mlb.classes_:
  df1[g].fillna("0.0", inplace = True) 

In [34]:
df1.dtypes

duration                    float64
director_facebook_likes     float64
actor_3_facebook_likes      float64
actor_1_facebook_likes      float64
genres                       object
facenumber_in_poster        float64
budget                      float64
actor_2_facebook_likes      float64
imdb_score                  float64
movie_facebook_likes          int64
content_rating_G              uint8
content_rating_GP             uint8
content_rating_M              uint8
content_rating_NC-17          uint8
content_rating_Not Rated      uint8
content_rating_PG             uint8
content_rating_PG-13          uint8
content_rating_Passed         uint8
content_rating_R              uint8
content_rating_TV-14          uint8
content_rating_TV-G           uint8
content_rating_TV-PG          uint8
content_rating_Unrated        uint8
content_rating_X              uint8
Action                       object
Adventure                    object
Animation                    object
Biography                   

In [35]:
df = df1

In [36]:
df.drop('genres',axis=1,inplace=True)

## Binning IMDb Rating

In [37]:
df["imdb_binned_score"]=pd.cut(df['imdb_score'], bins=[0,4,6,8,10], right=True, labels=False)+1

In [38]:
df.drop('imdb_score',axis=1,inplace=True)

# Preprocessing

In [39]:
df.columns

Index(['duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'facenumber_in_poster', 'budget',
       'actor_2_facebook_likes', 'movie_facebook_likes', 'content_rating_G',
       'content_rating_GP', 'content_rating_M', 'content_rating_NC-17',
       'content_rating_Not Rated', 'content_rating_PG', 'content_rating_PG-13',
       'content_rating_Passed', 'content_rating_R', 'content_rating_TV-14',
       'content_rating_TV-G', 'content_rating_TV-PG', 'content_rating_Unrated',
       'content_rating_X', 'Action', 'Adventure', 'Animation', 'Biography',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy',
       'Film-Noir', 'History', 'Horror', 'Music', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western',
       'imdb_binned_score'],
      dtype='object')

In [40]:
X=pd.DataFrame(columns=['duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'facenumber_in_poster', 'budget',
       'actor_2_facebook_likes', 'movie_facebook_likes',
       'content_rating_G', 'content_rating_GP', 'content_rating_M',
       'content_rating_NC-17', 'content_rating_Not Rated', 'content_rating_PG',
       'content_rating_PG-13', 'content_rating_Passed', 'content_rating_R',
       'content_rating_TV-14', 'content_rating_TV-G', 'content_rating_TV-PG',
       'content_rating_Unrated', 'content_rating_X', 'Action', 'Adventure',
       'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Family', 'Fantasy', 'Film-Noir', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western'] ,data=df)
y=pd.DataFrame(columns=['imdb_binned_score'],data=df)

## Label Encoder

In [41]:
from sklearn import preprocessing

In [42]:
lab = preprocessing.LabelEncoder()

In [43]:
y_transformed = lab.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Splitting the data into training and test data

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=100)

# Feature scaling

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Model

In [47]:
from sklearn import metrics

## Logistic Regression

In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
y_pred = logistic.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [82]:
y_pred = logistic.predict(X_test)

In [83]:
matrix = metrics.confusion_matrix(y_test, y_pred)

In [84]:
print(matrix)

[[  0  14  21   0]
 [  1  90 274   1]
 [  0  59 719   5]
 [  0   0  59   5]]


In [85]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6522435897435898


## KNN

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn = KNeighborsClassifier (n_neighbors=45)
knn.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=45)

In [78]:
knn_pred = knn.predict(X_test)

In [79]:
matrix = metrics.confusion_matrix(y_test, knn_pred)
print(matrix)
print("Accuracy:",metrics.accuracy_score(y_test, knn_pred))

[[  0   3  32   0]
 [  0  22 344   0]
 [  0  18 765   0]
 [  0   0  64   0]]
Accuracy: 0.6306089743589743


## SVC

In [86]:
from sklearn.svm import SVC

In [87]:
svc = SVC(kernel = 'sigmoid')

In [88]:
svc.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='sigmoid')

In [89]:
svc_pred = svc.predict(X_test)

In [90]:
matrix = metrics.confusion_matrix(y_test, svc_pred)
print(matrix)
print("Accuracy:",metrics.accuracy_score(y_test, svc_pred))

[[  0   7  28   0]
 [  0  44 322   0]
 [  0  51 730   2]
 [  0   3  60   1]]
Accuracy: 0.6209935897435898


## Naive Bayes

In [91]:
from sklearn.naive_bayes import GaussianNB

In [92]:
nb = GaussianNB()

In [94]:
nb.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [95]:
nb_pred = nb.predict(X_test)

In [96]:
matrix = metrics.confusion_matrix(y_test, nb_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, nb_pred))

[[  0   3  32   0]
 [  0  22 344   0]
 [  0  18 765   0]
 [  0   0  64   0]]
Accuracy: 0.07051282051282051


## Decision Tree

In [97]:
from sklearn.tree import DecisionTreeClassifier

In [98]:
dtree = DecisionTreeClassifier(criterion='gini')
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [99]:
dtree_pred = dtree.predict(X_test)

In [101]:
matrix = metrics.confusion_matrix(y_test, dtree_pred)
print(matrix)
print("Accuracy:",metrics.accuracy_score(y_test, dtree_pred))

[[  3  10  21   1]
 [ 17 149 196   4]
 [ 21 183 538  41]
 [  1   8  39  16]]
Accuracy: 0.5657051282051282


## Random Forest

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
rainforest = RandomForestClassifier(n_estimators = 200)

In [104]:
rainforest.fit(X_train, np.ravel(y_train,order='C'))

RandomForestClassifier(n_estimators=200)

In [105]:
rainforest_pred = rainforest.predict(X_test)

In [106]:
matrix = metrics.confusion_matrix(y_test, rainforest_pred)
print(matrix)
print("Accuracy:",metrics.accuracy_score(y_test, rainforest_pred))

[[  0  16  19   0]
 [  1 122 243   0]
 [  0  64 719   0]
 [  0   0  64   0]]
Accuracy: 0.6738782051282052


## Bagging

In [107]:
from sklearn.ensemble import BaggingClassifier

In [108]:
new_df = df.pop("imdb_binned_score")

In [109]:
bagging = BaggingClassifier(n_estimators=50, max_samples=.10 , oob_score=True)

In [110]:
bagging = bagging.fit(df, new_df)

In [111]:
print(bagging.oob_score_)

0.6859066859066859


## Gradient Boosting

In [112]:
from sklearn.ensemble import GradientBoostingClassifier

In [113]:
boosting = GradientBoostingClassifier(n_estimators = 50, learning_rate = 0.09, max_depth = 7)
boosting = boosting.fit(X_train,np.ravel(y_train,order='C'))

In [114]:
boosting_pred = boosting.predict(X_test)

In [116]:
matrix = metrics.confusion_matrix(y_test, boosting_pred)
print(matrix)
print("Accuracy:",metrics.accuracy_score(y_test, boosting_pred))

[[  0  17  18   0]
 [  1 155 209   1]
 [  1 106 668   8]
 [  0   1  49  14]]
Accuracy: 0.6706730769230769


## Model Comparison

In [117]:
from sklearn.metrics import classification_report

In [118]:
print('Logistic  Reports\n',classification_report(y_test, y_pred))
print('KNN Reports\n',classification_report(y_test, knn_pred))
print('SVC Reports\n',classification_report(y_test, svc_pred))
print('Naive BayesReports\n',classification_report(y_test, nb_pred))
print('Decision Tree Reports\n',classification_report(y_test, dtree_pred))
print('Random Forests Reports\n',classification_report(y_test, rainforest_pred))
print('Bagging Clasifier',bagging.oob_score_) 
print('Gradient Boosting',classification_report(y_test, boosting_pred))

Logistic  Reports
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        35
           2       0.55      0.25      0.34       366
           3       0.67      0.92      0.77       783
           4       0.45      0.08      0.13        64

    accuracy                           0.65      1248
   macro avg       0.42      0.31      0.31      1248
weighted avg       0.61      0.65      0.59      1248

KNN Reports
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        35
           2       0.51      0.06      0.11       366
           3       0.63      0.98      0.77       783
           4       0.00      0.00      0.00        64

    accuracy                           0.63      1248
   macro avg       0.29      0.26      0.22      1248
weighted avg       0.55      0.63      0.51      1248

SVC Reports
               precision    recall  f1-score   support

           1       0.00      0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat